import 'dotenv/config';
import { txFilter_Any, txFilter_Contract, txFilter_Standard } from '../verifier/utils/filter';
import { CredConfig } from '../utils/types';
import { ENDPOINT } from '../config';

const baseSettings = {
  network: 8453,
  startBlock: '0', // eligible network for your cred
  endBlock: 'latest',
  buyShareRoyalty: 100, // buy share royalty 1%
  sellShareRoyalty: 100, // sell royalty 1%
  quantity: 1, // initial share quantity
  verificationSource: 'https://github.com/PHI-LABS-INC/base-autumn',
};

export const credConfig: { [key: number]: CredConfig } = {
  0: {
    ...baseSettings,
    title: 'Number of transactions on Basechain',
    description: '[PHI-Season-0] Execute any transaction on Basechain',
    credType: 'ADVANCED',
    verificationType: 'SIGNATURE',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: 'any',
    methodId: 'any',
    filterFunction: txFilter_Any,
    mintEligibility: (result: number) => result > 0,
    transactionCountCondition: (txs: any[], address: string) =>
      txs.filter((tx) => tx.from.toLowerCase() === address.toLowerCase()).length,
    project: 'Base',
    tags: ['Transaction'],
    relatedLinks: ['https://base.org/'],
  },
  1: {
    ...baseSettings,
    title: 'Mint a brush to save your art on the canvas',
    description: 'Mint a Brush on Base Paint',
    credType: 'BASIC',
    verificationType: 'SIGNATURE',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0xD68fe5b53e7E1AbeB5A4d0A6660667791f39263a',
    methodId: 'any',
    filterFunction: txFilter_Any,
    mintEligibility: (result: number) => result > 0,
    transactionCountCondition: (txs: any[], address: string) =>
      txs.filter((tx) => tx.from.toLowerCase() === address.toLowerCase()).length,
    project: 'Base Paint',
    tags: ['Transaction', 'Base', 'Art'],
    relatedLinks: [
      'https://basepaint.xyz/brush',
      'https://basescan.org/address/0xD68fe5b53e7E1AbeB5A4d0A6660667791f39263a',
    ],
  },
  2: {
    ...baseSettings,
    title: '[Base] Trade Options on Stryke',
    description: 'Purchase Option on the Stryke platform',
    credType: 'BASIC',
    verificationType: 'SIGNATURE',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0x8C4D42ACdAf0dea678B02A092276E2313eD7D820',
    methodId: '0xac9650d8',
    filterFunction: txFilter_Standard,
    mintEligibility: (result: number) => result > 0,
    transactionCountCondition: (txs: any[], address: string) =>
      txs.filter((tx) => tx.from.toLowerCase() === address.toLowerCase()).length,
    project: 'Stryke',
    tags: ['DeFi', 'Option'],
    relatedLinks: ['https://www.stryke.xyz/en/dashboard'],
    verificationSource: 'https://github.com/PHI-LABS-INC/base-autumn',
  },
  3: {
    ...baseSettings,
    title: 'More than 5 transactions with Fren pet',
    description: 'Interact with Fren pet more than 5 times',
    credType: 'BASIC',
    verificationType: 'SIGNATURE',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0x0e22B5f3E11944578b37ED04F5312Dfc246f443C',
    methodId: 'any',
    filterFunction: txFilter_Contract,
    mintEligibility: (result: number) => result > 5,
    transactionCountCondition: (txs: any[], address: string) =>
      txs.filter((tx) => tx.from.toLowerCase() === address.toLowerCase()).length,
    project: 'Frenpet',
    tags: ['Gaming', 'Pet'],
    relatedLinks: ['https://frenpet.xyz/', 'https://basescan.org/address/0x0e22B5f3E11944578b37ED04F5312Dfc246f443C'],
  },
  4: {
    ...baseSettings,
    title: 'Deposit USDC in PoolTogether (Base)',
    description: 'Deposit USDC into PoolTogether on Base network',
    credType: 'BASIC',
    verificationType: 'SIGNATURE',
    apiChoice: 'contractCall',
    apiKeyOrUrl: '',
    contractAddress: '0x7f5C2b379b88499aC2B997Db583f8079503f25b9',
    functionName: 'balanceOf',
    abi: [
      {
        name: 'balanceOf',
        type: 'function',
        inputs: [
          {
            name: '_account',
            type: 'address',
          },
        ],
        outputs: [
          {
            name: '',
            type: 'uint256',
          },
        ],
        stateMutability: 'view',
      },
    ],
    contractCallCondition: (result: number) => result > 0,
    project: 'PoolTogether',
    tags: ['DeFi', 'Savings'],
    relatedLinks: ['https://app.cabana.fi/vault/8453/0x7f5C2b379b88499aC2B997Db583f8079503f25b9'],
  },
  5: {
    ...baseSettings,
    title: 'Create on chain Activity on DOT',
    description: 'Perform an on-chain activity on DOT platform',
    credType: 'BASIC',
    verificationType: 'SIGNATURE',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0x7b5673B598A71d27a56781271eC5fa05DE216df0',
    methodId: 'any', // 0x72c275a4
    filterFunction: txFilter_Contract,
    mintEligibility: (result: number) => result > 0,
    transactionCountCondition: (txs: any[], address: string) =>
      txs.filter((tx) => tx.from.toLowerCase() === address.toLowerCase()).length,
    project: 'DOT',
    tags: ['Social'],
    relatedLinks: ['https://dot.fan/'],
  },
  6: {
    ...baseSettings,
    title: 'Holder of a Vrbs',
    description: 'Own at least one Vrbs token',
    credType: 'BASIC',
    verificationType: 'SIGNATURE',
    apiChoice: 'contractCall',
    apiKeyOrUrl: '',
    contractAddress: '0x9ea7fd1B8823a271BEC99b205B6c0C56d7C3eAe9',
    functionName: 'balanceOf',
    abi: [
      {
        name: 'balanceOf',
        type: 'function',
        inputs: [
          {
            name: 'account',
            type: 'address',
          },
        ],
        outputs: [
          {
            name: '',
            type: 'uint256',
          },
        ],
        stateMutability: 'view',
      },
    ],
    contractCallCondition: (result: number) => result > 0,
    project: 'Vrbs',
    tags: ['NFT'],
    relatedLinks: [
      'https://vrbs.build/vrbs/auction',
      'https://basescan.org/address/0x9ea7fd1b8823a271bec99b205b6c0c56d7c3eae9',
    ],
  },
  7: {
    ...baseSettings,
    title: 'Create and Mint on paragraph.xyz',
    description: 'Create and mint content on paragraph.xyz',
    credType: 'BASIC',
    verificationType: 'SIGNATURE',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0x9Bf9D0D88C1A835F1052Ef0FBa325b35bBea127a',
    methodId: '0x3a81b8a5',
    filterFunction: txFilter_Standard,
    mintEligibility: (result: number) => result > 0,
    transactionCountCondition: (txs: any[], address: string) =>
      txs.filter((tx) => tx.from.toLowerCase() === address.toLowerCase()).length,
    project: 'paragraph.xyz',
    tags: ['Content', 'NFT'],
    relatedLinks: ['https://paragraph.xyz/discover/feed/recent/paragraph'],
  },
  8: {
    ...baseSettings,
    title: 'Create Collection on Zora (Base)',
    description: 'Create a new collection on Zora on Base network',
    credType: 'BASIC',
    verificationType: 'SIGNATURE',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0x777777C338d93e2C7adf08D102d45CA7CC4Ed021',
    methodId: '0x0582823a',
    filterFunction: txFilter_Standard,
    mintEligibility: (result: number) => result > 0,
    transactionCountCondition: (txs: any[], address: string) =>
      txs.filter((tx) => tx.from.toLowerCase() === address.toLowerCase()).length,
    project: 'Zora',
    tags: ['NFT'],
    relatedLinks: ['https://zora.co/'],
  },
  9: {
    ...baseSettings,
    title: 'Execute Swap on Uniswap (Base)',
    description: 'Perform a token swap on Uniswap on Base network',
    credType: 'BASIC',
    verificationType: 'SIGNATURE',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0x3fC91A3afd70395Cd496C647d5a6CC9D4B2b7FAD',
    methodId: '0x3593564c',
    filterFunction: txFilter_Standard,
    mintEligibility: (result: number) => result > 0,
    transactionCountCondition: (txs: any[], address: string) =>
      txs.filter((tx) => tx.from.toLowerCase() === address.toLowerCase()).length,
    project: 'Uniswap',
    tags: ['DeFi', 'Swap'],
    relatedLinks: ['https://app.uniswap.org/'],
  },
  10: {
    ...baseSettings,
    title: 'Deposit ETH to Seamless and leverage',
    description: 'Deposit ETH and create a leveraged position on Seamless',
    credType: 'BASIC',
    verificationType: 'SIGNATURE',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0x5Ed6167232b937B0A5C84b49031139F405C09c8A',
    methodId: '0xbc157ac1',
    filterFunction: txFilter_Standard,
    mintEligibility: (result: number) => result > 0,
    transactionCountCondition: (txs: any[], address: string) =>
      txs.filter((tx) => tx.from.toLowerCase() === address.toLowerCase()).length,
    project: 'Seamless',
    tags: ['DeFi', 'Leverage'],
    relatedLinks: [
      'https://app.seamlessprotocol.com/#/?tab=Earn&asset=0x4200000000000000000000000000000000000006-0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
    ],
  },
  11: {
    ...baseSettings,
    title: 'Execute Swap on Rainbow (Base)',
    description: 'Perform a token swap on Rainbow on Base network',
    credType: 'BASIC',
    verificationType: 'SIGNATURE',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0x00000000009726632680FB29d3F7A9734E3010E2',
    methodId: '0x999b6464',
    filterFunction: txFilter_Standard,
    mintEligibility: (result: number) => result > 0,
    transactionCountCondition: (txs: any[], address: string) =>
      txs.filter((tx) => tx.from.toLowerCase() === address.toLowerCase()).length,
    project: 'rainbow',
    tags: ['Wallet'],
    relatedLinks: ['https://rainbow.me/'],
  },
  12: {
    ...baseSettings,
    title: 'Mint bsdETH in Reserve Protocol (Base)',
    description: 'Mint bsdETH token in Reserve Protocol on Base network',
    credType: 'BASIC',
    verificationType: 'SIGNATURE',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0xe811b62AB97d9370cE2e25F9ceBC904522b81FE1',
    methodId: '0xdd074ea0',
    filterFunction: txFilter_Standard,
    mintEligibility: (result: number) => result > 0,
    transactionCountCondition: (txs: any[], address: string) =>
      txs.filter((tx) => tx.from.toLowerCase() === address.toLowerCase()).length,
    project: 'Reserve Protocol',
    tags: ['DeFi', 'Stablecoin'],
    relatedLinks: [
      'https://app.reserve.org/base/token/0xcb327b99ff831bf8223cced12b1338ff3aa322ff/overview',
      'https://basescan.org/address/0xe811b62ab97d9370ce2e25f9cebc904522b81fe1',
    ],
  },
  13: {
    ...baseSettings,
    title: 'Add Liquidity on Aerodrome (Base)',
    description: 'Add liquidity to a pool on Aerodrome on Base network',
    credType: 'BASIC',
    verificationType: 'SIGNATURE',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0xcF77a3Ba9A5CA399B7c97c74d54e5b1Beb874E43',
    methodId: ['0xb7e0d4c0', '0x5a47ddc3'],
    filterFunction: txFilter_Standard,
    mintEligibility: (result: number) => result > 0,
    transactionCountCondition: (txs: any[], address: string) =>
      txs.filter((tx) => tx.from.toLowerCase() === address.toLowerCase()).length,
    project: 'Aerodrome',
    tags: ['DeFi', 'Liquidity'],
    relatedLinks: [
      'https://aerodrome.finance/pools',
      'https://basescan.org/address/0xcf77a3ba9a5ca399b7c97c74d54e5b1beb874e43',
    ],
  },
  14: {
    ...baseSettings,
    title: 'Holder of Brett Token',
    description: 'Own at least one Brett Token',
    credType: 'ADVANCED',
    verificationType: 'SIGNATURE',
    apiChoice: 'contractCall',
    apiKeyOrUrl: '',
    contractAddress: '0x532f27101965dd16442E59d40670FaF5eBB142E4',
    functionName: 'balanceOf',
    abi: [
      {
        name: 'balanceOf',
        type: 'function',
        inputs: [
          {
            name: 'account',
            type: 'address',
          },
        ],
        outputs: [
          {
            name: '',
            type: 'uint256',
          },
        ],
        stateMutability: 'view',
      },
    ],
    contractCallCondition: (result: number) => result > 0,
    project: 'Brett Token',
    tags: ['Token', 'Holder'],
    relatedLinks: [
      'https://www.basedbrett.com/',
      'https://basescan.org/address/0x532f27101965dd16442e59d40670faf5ebb142e4#readContract',
    ],
  },
};

export const credVerifyEndpoint: { [key: number]: string } = Object.fromEntries(
  Object.keys(credConfig).map((key) => [key, `https://${ENDPOINT}/api/verify/${key}`]),
);
